#!/bin/sh

vol=$( { i2cget -y 1 0x48 15; } 2>&1 )
vol=${vol:2}
volume=$(printf "%d\n" "0x"$( echo $vol ))
volume=`expr $volume + 1`
if (( $volume < 100 )); then
i2cset -y 1 0x48 15 $volume
i2cset -y 1 0x48 16 $volume
fi
echo $volume > /root/vol
